# coding: gbk
"""Read-only diagnostics for the Big QMT embedded Python runtime.

This module intentionally has no order or cancel calls. It can query account
state, contract data and history, subscribe to one tick stream, and print the
native account/order/trade callbacks generated by other activity.
"""

import importlib
import time


LOG_PREFIX = "[lean_qmt_probe]"
ACCOUNT_TYPE = "STOCK"
HISTORY_FIELDS = ["time", "open", "high", "low", "close", "volume"]

_account_id = ""
_get_trade_detail_data_function = None
_quote_subscription_id = None
_quote_count = 0


def _log(message, **fields):
    parts = [LOG_PREFIX, str(message)]
    for field_name in sorted(fields):
        parts.append("%s=%s" % (field_name, fields[field_name]))
    print(" ".join(parts))


def _load_config():
    try:
        import qmt_local_config as local_config
    except ImportError:
        return "", "000001.SZ", True

    local_config = importlib.reload(local_config)

    return (
        str(getattr(local_config, "ACCOUNT_ID", "") or "").strip(),
        str(
            getattr(local_config, "PROBE_STOCK_CODE", "000001.SZ")
            or "000001.SZ"
        ).strip(),
        bool(getattr(local_config, "SUBSCRIBE_TICKS", True)),
    )


def _attribute(value, attribute_names, default=""):
    for attribute_name in attribute_names:
        try:
            attribute_value = getattr(value, attribute_name)
        except Exception:
            continue
        if attribute_value is not None:
            return attribute_value
    return default


def _collection_size(value):
    if value is None:
        return 0
    try:
        return len(value)
    except Exception:
        return 1


def _query_trade_detail(detail_type):
    if _get_trade_detail_data_function is None:
        _log("query_unavailable", type=detail_type)
        return None

    started_at = time.time()
    try:
        try:
            result = _get_trade_detail_data_function(
                _account_id,
                ACCOUNT_TYPE,
                detail_type,
                "",
            )
        except TypeError:
            result = _get_trade_detail_data_function(
                _account_id,
                ACCOUNT_TYPE,
                detail_type,
            )
    except Exception as error:
        _log(
            "query_failed",
            error=repr(error),
            type=detail_type,
        )
        return None

    _log(
        "query_ok",
        elapsed_ms=int((time.time() - started_at) * 1000),
        rows=_collection_size(result),
        type=detail_type,
    )
    return result


def _log_account_summary(account_rows):
    if not account_rows:
        return
    try:
        account = account_rows[0]
    except Exception:
        account = account_rows
    _log(
        "account_summary",
        cash=_attribute(
            account,
            ("m_dAvailable", "m_dCash", "cash", "available_cash"),
        ),
        market_value=_attribute(
            account,
            ("m_dMarketValue", "market_value"),
        ),
        total_asset=_attribute(
            account,
            ("m_dBalance", "m_dTotalAsset", "total_asset"),
        ),
    )


def _query_contract(context_info, stock_code):
    method = getattr(context_info, "get_instrumentdetail", None)
    if not callable(method):
        _log("contract_query_unavailable", stock_code=stock_code)
        return
    try:
        detail = method(stock_code) or {}
        instrument_name = ""
        if isinstance(detail, dict):
            instrument_name = detail.get("InstrumentName", "")
        _log(
            "contract_query_ok",
            instrument_name=instrument_name,
            stock_code=stock_code,
        )
    except Exception as error:
        _log(
            "contract_query_failed",
            error=repr(error),
            stock_code=stock_code,
        )


def _query_history(context_info, stock_code):
    method = getattr(context_info, "get_market_data_ex", None)
    if not callable(method):
        _log("history_unavailable", stock_code=stock_code)
        return
    started_at = time.time()
    try:
        history = method(
            fields=list(HISTORY_FIELDS),
            stock_code=[stock_code],
            period="1d",
            start_time="",
            end_time="",
            count=5,
            dividend_type="none",
            fill_data=True,
            subscribe=False,
        )
        _log(
            "history_ok",
            elapsed_ms=int((time.time() - started_at) * 1000),
            result_type=type(history).__name__,
            stock_code=stock_code,
        )
    except Exception as error:
        _log(
            "history_failed",
            error=repr(error),
            stock_code=stock_code,
        )


def _subscribe_ticks(context_info, stock_code):
    global _quote_subscription_id

    method = getattr(context_info, "subscribe_quote", None)
    if not callable(method):
        _log("quote_subscription_unavailable", stock_code=stock_code)
        return
    try:
        _quote_subscription_id = method(
            stock_code,
            "tick",
            "none",
            _quote_callback,
        )
        _log(
            "quote_subscription_ok",
            stock_code=stock_code,
            subscription_id=_quote_subscription_id,
        )
    except Exception as error:
        _log(
            "quote_subscription_failed",
            error=repr(error),
            stock_code=stock_code,
        )


def _quote_callback(data):
    global _quote_count

    _quote_count += 1
    if _quote_count <= 3 or _quote_count % 100 == 0:
        _log(
            "quote_callback",
            count=_quote_count,
            result_type=type(data).__name__,
        )


def init(
    context_info,
    get_trade_detail_data_function=None,
    injected_account_id="",
):
    global _account_id
    global _get_trade_detail_data_function

    configured_account_id, stock_code, subscribe_ticks = _load_config()
    _account_id = configured_account_id or str(injected_account_id or "").strip()
    _get_trade_detail_data_function = get_trade_detail_data_function

    _log(
        "init_start",
        account_configured=bool(_account_id),
        stock_code=stock_code,
    )

    if not _account_id:
        _log(
            "account_missing",
            action="create_qmt_local_config.py",
        )
        return

    set_account = getattr(context_info, "set_account", None)
    if not callable(set_account):
        _log("set_account_unavailable")
        return

    try:
        set_account(_account_id)
        _log("set_account_ok")
    except Exception as error:
        _log("set_account_failed", error=repr(error))
        return

    account_rows = _query_trade_detail("ACCOUNT")
    _log_account_summary(account_rows)
    _query_trade_detail("POSITION")
    _query_trade_detail("ORDER")
    _query_trade_detail("DEAL")
    _query_contract(context_info, stock_code)
    _query_history(context_info, stock_code)
    if subscribe_ticks:
        _subscribe_ticks(context_info, stock_code)
    _log("init_complete")


def handlebar(context_info):
    return None


def account_callback(context_info, account_info):
    _log(
        "account_callback",
        status=_attribute(account_info, ("m_strStatus", "status")),
    )


def order_callback(context_info, order_info):
    _log(
        "order_callback",
        order_status=_attribute(
            order_info,
            ("m_nOrderStatus", "order_status", "status"),
        ),
        order_sys_id=_attribute(
            order_info,
            ("m_strOrderSysID", "order_sys_id", "order_id"),
        ),
        traded_volume=_attribute(
            order_info,
            ("m_nVolumeTraded", "traded_volume"),
        ),
    )


def deal_callback(context_info, deal_info):
    _log(
        "deal_callback",
        order_sys_id=_attribute(
            deal_info,
            ("m_strOrderSysID", "order_sys_id", "order_id"),
        ),
        price=_attribute(deal_info, ("m_dPrice", "price")),
        trade_id=_attribute(deal_info, ("m_strTradeID", "trade_id")),
        volume=_attribute(deal_info, ("m_nVolume", "volume")),
    )


def position_callback(context_info, position_info):
    _log(
        "position_callback",
        stock_code=_attribute(
            position_info,
            ("m_strInstrumentID", "stock_code"),
        ),
        volume=_attribute(
            position_info,
            ("m_nVolume", "volume"),
        ),
    )


def order_error_callback(context_info, order_args, error_message):
    _log(
        "order_error_callback",
        error_message=str(error_message or ""),
    )
